# Generated by Django 4.0.2 on 2022-02-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.CharField(max_length=10, verbose_name='Дата публикации'),
        ),
    ]
